//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubExtension.Templates.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
