// <auto-generated />
namespace GitHubExtension.Security.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddField_IsMailVisible : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddField_IsMailVisible));
        
        string IMigrationMetadata.Id
        {
            get { return "201604251106316_AddField_IsMailVisible"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
