//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubExtension.Activity.Internal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityEvent
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int CurrentRepositoryId { get; set; }
        public int ActivityTypeId { get; set; }
        public Nullable<System.DateTime> InvokeTime { get; set; }
        public string Message { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual Users Users { get; set; }
    }
}
