//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitHubExtension.Activity.DAL
{
    using System;
    
    public enum ActivityType : int
    {
        AddRole = 0,
        ChangeRole = 1,
        JoinToSystem = 2,
        Comment = 3
    }
}
