#%RAML 0.8
title: GitHubExtension
baseUri: http://localhost:50859/api
version: v1

/Account: !include account.raml
/activity: !include activity.raml
/note: !include note.raml
/repos: !include repos.raml
/roles: !include roles.raml
/templates: !include templates.raml
/user: !include user.raml
