#%RAML 0.8 Resource
post:
  description: Create note about chosen collaborator
  body:
    application/json:
      example: |
        {
          "CollaboratorId": "550e8400-e29b-41d4-a716-446655440000",
          "Body": "Great coder!"
        }
      schema: |
        {
          "type": "object",
          "required": true,
          "properties": {
            "CollaboratorId": {
                "type": "string",
                "required": true
            },
            "Body": {
                "type": "string",
                "required": true
            }
          }
        }
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "$id": "1",
              "id": 1,
              "userId": "550e8400-e29b-41d4-a716-446655441111",
              "collaboratorId": "550e8400-e29b-41d4-a716-446655440000",
              "body": "Great coder!",
              "collaborator": null,
              "user": null
            }
    400:
      body:
        application/json:
          example: |
            {
              "$id": "1",
              "message": "The request is invalid.",
              "modelState": {
                "$id": "2",
                "model.CollaboratorId": [
                "'Collaborator Id' must not be empty."
                ],
                "model.Body": [
                  "'Body' must not be empty",
                  "'Body' must be between 5 and 2048 characters. You entered 0 characters."
                ]
              }
            }
    401:
      body:
        application/json:
          example: |
            {
              "$id": "1",
              "message": "Authorization has been denied for this request."
            }
/collaborators/{collaboratorId}:
  get:
    description: Get note of user about chosen collaborator
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "$id": "1",
                "body": "Great coder!",
                "collaboratorId": "550e8400-e29b-41d4-a716-446655440000",
                "userId": "550e8400-e29b-41d4-a716-446655441111"
              }
      401:
        body:
          application/json:
            example: |
              {
                "$id": "1",
                "message": "Authorization has been denied for this request."
              }
      404:
