CREATE TABLE [dbo].[Notes]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[UserId] NVARCHAR (128) NOT NULL,
	[CollaboratorId] NVARCHAR (128) NOT NULL,
	[Body] NVARCHAR (1024) NULL,
	CONSTRAINT PK_Notes_Id PRIMARY KEY (Id)	
)
